name: Run Cypress Tests

on:
  push:
    branches:
      - main  # ou a branch que você deseja monitorar
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # ou a versão que você está usando

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      run: npx cypress run